### ISSUE TITLE
Checkpoint 1

### ISSUE THREAD

**Issue by Carlos-Leon98** [Carlos-Leon98/Inventory-Management-System#1]
Good evening Teacher, 

The first checkpoint is ready to be reviewed. Currently still working on the mocks for the screen design, but once I have them I will upload them.

Thank you,
Carlos Leon Rivas.

**Comment by pawaitemadisoncollege** [comment]
Hi @Carlos-Leon98 

Thanks for sharing your indie project checkpoint 1!  This checkpoint needs some work as some areas need to be improved and others are incomplete. 

Following are my observations and suggestions:

**Problem statement**

I suspect there are a lot of inventory applications available. Your problem statement would be improved if it clearly presented the problem with those systems, and how your application will address those weaknesses. 

- [ ] Did you happen to use AI to write your problem statement? To me, it reads a bit unnaturally, and overemphasizes the technology used rather than explaining what the application will actually do. 
- [ ] Consider your user stories, and craft your problem statement around what your application will do. 

**User stories**

Your MVP user stories meets _some_ of the project requirement and are clearly stated.

- [ ] I do not see a user story that addresses a delete scenario. Is there a meaningful story you can add that would include deleting? 
- [ ] Should have a sign out user story too.
- [ ] Is there a user story that involves the web service/s that you will be implementing?

**Project plan**

- [ ] I noticed you had tasks for user registration and sign up - we I'll be using AWS Cognito for this. The screens and much of the work will be provided by AWS, so I recommend holding off on this until week 7 when you will compete an exercise with Cognito. 
- [ ] Please add some dates to your plan so that it is clear when you will be completing the various items listed. 
- [ ] I recommend taking a look at checkpoints 2 and 3, identifying the tasks you need to complete to achieve those checkpoints and add those tasks to your plan.

**Screen design**

- [ ] Screens appear to be missing. Can you point me to these? Be sure all user stories are covered by the screens. 

**Reflection statements/Time Log**

- [ ] This appears to be missing. There is a file, but no time has been entered. You should be tracking on all time spent in this course. Be sure to start doing this right away - we are already through 4 weeks!

**Comment by Carlos-Leon98** [comment]
Good evening @pawaitemadisoncollege,

Sorry for replying this late. I will take point by point from the feedback you provided.

Problem statement

I suspect there are a lot of inventory applications available. Your problem statement would be improved if it clearly presented the problem with those systems, and how your application will address those weaknesses.

-  Did you happen to use AI to write your problem statement? To me, it reads a bit unnaturally, and overemphasizes the technology used rather than explaining what the application will actually do.

I had my initial Problem Statement at the beginning of the project, explaining that I would like to automate some of the regular inventory processes, and when I checked the requirements for checkpoint 1 I thought I could improve the problem statement. Then, I thought I could use AI to improve the wording and the way I could present the Problem Statement. I can try getting back to the previous Problem Statement I had.

-  Consider your user stories, and craft your problem statement around what your application will do.

The user stories I set are a high level of what I want this application to do. Of course, there are more things I plan to add and others that I still considering. Do you think I should try to add a full description of what I want for each story, including an acceptance criteria?

User stories

Your MVP user stories meets some of the project requirement and are clearly stated.

-  I do not see a user story that addresses a delete scenario. Is there a meaningful story you can add that would include deleting?

I am still considering that part. Usually, I've run into cases where the product information is not deleted but is archived (it is disabled), because the business wants to keep that information for a certain period of time until there is an agreement to finally delete it.

-  Should have a sign out user story too.

You are right, I forgot about logging out. I will add it.

-  Is there a user story that involves the web service/s that you will be implementing?

There is not yet, I was planning using API Gateway from AWS.


Project plan

-  I noticed you had tasks for user registration and sign up - we I'll be using AWS Cognito for this. The screens and much of the work will be provided by AWS, so I recommend holding off on this until week 7 when you will compete an exercise with Cognito.
-  Please add some dates to your plan so that it is clear when you will be completing the various items listed.
-  I recommend taking a look at checkpoints 2 and 3, identifying the tasks you need to complete to achieve those checkpoints and add those tasks to your plan.


Screen design

-  Screens appear to be missing. Can you point me to these? Be sure all user stories are covered by the screens.


Reflection statements/Time Log

-  This appears to be missing. There is a file, but no time has been entered. You should be tracking on all time spent in this course. Be sure to start doing this right away - we are already through 4 weeks!




||||||||||||||||||||||||||

Currently working on the feedback you provide me to add the user stories you recommend, and also, adding the screenshots. I will letting you know once I am done with the updates.


Thank you,
Carlos Leon Rivas.

**Comment by Carlos-Leon98** [comment]
Good evening @pawaitemadisoncollege, 

I update as much as possible based on your feedback provided. 

This following week is the starting of development, I am still considering I am behind on where on the project I am should be but I am currently working to be on date.

Thank you,
Carlos Leon Rivas.

**Comment by pawaitemadisoncollege** [comment]
Hi @Carlos-Leon98 

Thanks for updating the **user stories** with a delete scenario.

- [ ] With regard to a service - the idea is to consume an external service, so I am not sure how API Gateway fits into this? Are you planning to write a service that your application will then consume. 
- [ ] The project requirement is for more than a single one-to-many relationship. Based on your user stories, will you meet that? 
- [ ] It looks like there is an analytics button in the screens, but I am not sure which user story/ies relate to this?

**Project plan**

- [ ] Does not appear to be updated. Refer to the fat bike trail reports for an example of the level of detail you might include per user story.

**Time log**

- [ ] Remember to update regularly - it should include all time spent in this class, including weekly exercises, readings, watchings, peer review, etc.

**Comment by Carlos-Leon98** [comment]
Hi @pawaitemadisoncollege, 

I am re-opening this issue since I want to confirm I meet the requirements for checkpoint 1.

I have a few questions regarding your feedback.

- [ ]  With regard to a service - the idea is to consume an external service, so I am not sure how API Gateway fits into this? Are you planning to write a service that your application will then consume.

Question - That was my plan, now I am kind of worried about whether I will meet the basis requirements of the indie project.

- [ ]  The project requirement is for more than a single one-to-many relationship. Based on your user stories, will you meet that?

Question - Since I showed how my database structure is, do you think it will meet the requirement or is there any suggestion?

Thank you,
Carlos Leon Rivas.

**Comment by Carlos-Leon98** [comment]
Good afternoon @pawaitemadisoncollege,

I already completed the project plan and currently working on all necessary user stories, but I would like your feedback on my project plan in the mean time.

https://github.com/Carlos-Leon98/Inventory-Management-System/blob/main/ProjectPlan.md
